# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import nhi1
import imagenhi
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 422)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(220, 340, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(11)
        self.button2.setFont(font)
        self.button2.setStyleSheet("background-color: rgb(76, 199, 255);\n"
"color: rgb(255, 255, 255);")
        self.button2.setObjectName("button2")
        self.background = QtWidgets.QPushButton(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(80, 30, 421, 241))
        self.background.setStyleSheet("border-image: url(:/myimage/image/background3.jpg);")
        self.background.setText("")
        self.background.setObjectName("background")
        self.Sound_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Sound_2.setGeometry(QtCore.QRect(530, 10, 41, 31))
        self.Sound_2.setStyleSheet("image:url(:/myimage/image/sound_on.png);\n"
"background-color: rgb(76, 199, 255);\n"
"")
        self.Sound_2.setText("")
        self.Sound_2.setObjectName("Sound_2")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(220, 280, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(11)
        self.button1.setFont(font)
        self.button1.setStyleSheet("background-color: rgb(76, 199, 255);\n"
"color: rgb(255, 255, 255);")
        self.button1.setObjectName("button1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 579, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button1.clicked.connect(self.show_second_window_A)
        self.button2.clicked.connect(self.show_second_window_B)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">2 PLAYERS </span></p></body></html>"))
        self.button2.setText(_translate("MainWindow", "2 PLAYERS"))
        self.button1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">1 PLAYERS</span></p></body></html>"))
        self.button1.setText(_translate("MainWindow", "1 PLAYER"))

    def show_second_window_A(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = nhi1.Ui_MainWindowA()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.deleteLater()
        
    def show_second_window_B(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = nhi1.Ui_MainWindowB()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.deleteLater()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())