# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'play.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import imagenhi1
class Ui_MainWindowA(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 433)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Sound_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Sound_2.setGeometry(QtCore.QRect(530, 10, 41, 31))
        self.Sound_2.setStyleSheet("image:url(:/myimage/image/sound_on.png)i;\n"
"background-color: rgb(76, 199, 255);\n"
"")
        self.Sound_2.setText("")
        self.Sound_2.setObjectName("Sound_2")
        self.A = QtWidgets.QPushButton(self.centralwidget)
        self.A.setGeometry(QtCore.QRect(20, 90, 511, 271))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.A.setFont(font)
        self.A.setStyleSheet("color: rgb(255, 85, 255);")
        self.A.setObjectName("A")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 581, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.A.setText(_translate("MainWindow", "A"))
        
        
class Ui_MainWindowB(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 433)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Sound_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Sound_2.setGeometry(QtCore.QRect(530, 10, 41, 31))
        self.Sound_2.setStyleSheet("image:url(:/myimage/image/sound_on.png)i;\n"
"background-color: rgb(76, 199, 255);\n"
"")
        self.Sound_2.setText("")
        self.Sound_2.setObjectName("Sound_2")
        self.B = QtWidgets.QPushButton(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(20, 90, 511, 271))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B.setFont(font)
        self.B.setStyleSheet("color: rgb(255, 85, 255);")
        self.B.setObjectName("B")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 581, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.B.setText(_translate("MainWindow", "B"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowA()
    ui = Ui_MainWindowB()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
